#pragma once
#include <string>
#include <vector>

struct VisionEffect
{
	std::string VisionName;
	std::string fxname;
	std::string fxname2;
	std::string ptfx;
};
static std::vector<VisionEffect> effectname =
{
	{ "Clown Appears","scr_rcbarry2", "scr_rcbarry2", "scr_clown_appears" },
{ "Firework 1","scr_indep_fireworks", "scr_indep_fireworks", "scr_indep_firework_trailburst" },
{ "Firework 2","proj_xmas_firework", "proj_xmas_firework", "scr_firework_xmas_burst_rgw" },
{ "Firework 3","proj_xmas_firework", "proj_xmas_firework", "scr_firework_xmas_spiral_burst_rgw" },
{ "Banknotes","scr_ornate_heist", "scr_ornate_heist", "scr_heist_ornate_banknotes" },
{ "Truck Crash","scr_fbi4", "scr_fbi4", "scr_fbi4_trucks_crash" },
{ "Alien 1","scr_rcbarry1", "scr_rcbarry1", "scr_alien_disintegrate" },
{ "Alien 2","scr_rcbarry1", "scr_rcbarry1", "scr_alien_teleport" },
{ "Electric Box","scr_agencyheistb", "scr_agencyheistb", "scr_agency3b_elec_box" },
{ "Water Splash","scr_fbi5a", "scr_fbi5a", "scr_fbi5_ped_water_splash" },
{ "Bubbles","scr_fbi5a", "scr_fbi5a", "water_splash_ped_bubbles" },
{ "Blood Entry","scr_finalec2", "scr_finalec2", "scr_finale2_blood_entry" },
{ "Sniper Impact","scr_martin1", "scr_martin1", "scr_sol1_sniper_impact" },
{ "Dirt Throw","core_snow", "core_snow", "cs_mich1_spade_dirt_throw" },
{ "Blood Stab","scr_michael2", "scr_michael2", "scr_mich2_blood_stab" },
{ "Ped Sliced","scr_michael2", "scr_michael2", "scr_abattoir_ped_sliced" },
{ "Camera","scr_rcpaparazzo1", "scr_rcpaparazzo1", "scr_rcpap1_camera" },
{ "Meth Smoke","scr_familyscenem", "scr_familyscenem", "scr_meth_pipe_smoke" },
{ "Burial Dirt","scr_reburials", "scr_reburials", "scr_burial_dirt" },
//Night Club
{ "scr_sh_lighter_sparks","scr_safehouse", "scr_safehouse", "scr_sh_lighter_sparks" },
{ "scr_sh_lighter_flame","scr_safehouse", "scr_safehouse", "scr_sh_lighter_flame" },
{ "scr_sh_cig_smoke","scr_safehouse", "scr_safehouse", "scr_sh_cig_smoke" },
{ "scr_sh_cig_exhale_mouth","scr_safehouse", "scr_safehouse", "scr_sh_cig_exhale_mouth" },
{ "scr_sh_cig_exhale_nose","scr_safehouse", "scr_safehouse", "scr_sh_cig_exhale_nose" },
{ "scr_sh_cig_exhale_nose","scr_safehouse", "scr_safehouse", "scr_sh_cig_exhale_nose" },

//
{ "scr_ie_jug_mask_flame","scr_impexp_jug","scr_impexp_jug","scr_ie_jug_mask_flame" },
{ "scr_ie_jug_mask_flame","scr_impexp_jug","scr_impexp_jug","scr_ie_jug_mask_flame" },
{ "scr_impexp_tw_take_zone","scr_ie_tw","scr_ie_tw","scr_impexp_tw_take_zone" },
{ "scr_sr_lg_take_zone","scr_sr_adversary","scr_sr_adversary","scr_sr_lg_take_zone" },
{ "scr_powerplay_beast_vanish","scr_powerplay","scr_powerplay","scr_powerplay_beast_vanish" },
{ "scr_powerplay_beast_appear","scr_powerplay","scr_powerplay","scr_powerplay_beast_appear" },
{ "scr_powerplay_beast_vanish","scr_powerplay","scr_powerplay","scr_powerplay_beast_vanish" },
{ "scr_powerplay_beast_appear","scr_powerplay","scr_powerplay","scr_powerplay_beast_appear" },
{ "scr_adversary_trail_lightning","scr_bike_adversary","scr_bike_adversary","scr_adversary_trail_lightning" },
{ "scr_stunts_bomb_fuse","scr_stunts","scr_stunts","scr_stunts_bomb_fuse" },

{ "scr_indep_firework_starburst","scr_indep_fireworks","scr_indep_fireworks","scr_indep_firework_starburst" },
{ "scr_indep_firework_fountain","scr_indep_fireworks","scr_indep_fireworks","scr_indep_firework_fountain" },
{ "scr_indep_firework_shotburst","scr_indep_fireworks","scr_indep_fireworks","scr_indep_firework_shotburst" },
{ "scr_ba_bomb_destroy","scr_ba_bomb","scr_ba_bomb","scr_ba_bomb_destroy" },

{ "scr_lowrider_flare","scr_lowrider","scr_lowrider","scr_lowrider_flare" },
{ "scr_heist_biolab_flare","scr_biolab_heist","scr_biolab_heist","scr_heist_biolab_flare" },
{ "scr_heist_biolab_flare_underwater","scr_biolab_heist","scr_biolab_heist","scr_heist_biolab_flare_underwater" },
{ "scr_adversary_gunsmith_weap_change","scr_bike_adversary","scr_bike_adversary","scr_adversary_gunsmith_weap_change" },
{ "scr_ie_vv_vehicle_damage","scr_ie_vv","scr_ie_vv","scr_ie_vv_vehicle_damage" },
{ "scr_ie_vv_muzzle_flash","scr_ie_vv","scr_ie_vv","scr_ie_vv_muzzle_flash" },
{ "scr_sr_tr_car_change","scr_sr_tr","scr_sr_tr","scr_sr_tr_car_change" },
{ "scr_powerplay_beast_appear","scr_powerplay","scr_powerplay","scr_powerplay_beast_appear" },
{ "scr_xm_submarine_surface_splashes","scr_xm_submarine","scr_xm_submarine","scr_xm_submarine_surface_splashes" },
{ "scr_xm_submarine_surface_explosion","scr_xm_submarine","scr_xm_submarine","scr_xm_submarine_surface_explosion" },
{ "scr_xm_submarine_surface_explosion","scr_xm_submarine","scr_xm_submarine","scr_xm_submarine_surface_explosion" },
{ "scr_ar_trail_smoke","scr_ar_planes","scr_ar_planes","scr_ar_trail_smoke" },
{ "scr_ar_trail_smoke_slow","scr_ar_planes","scr_ar_planes","scr_ar_trail_smoke_slow" },
{ "scr_ie_jug_mask_steam","scr_impexp_jug","scr_impexp_jug","scr_ie_jug_mask_steam" },
{ "scr_impexp_jug_outfit_swap","scr_impexp_jug","scr_impexp_jug","scr_impexp_jug_outfit_swap" },
{ "scr_powerplay_beast_vanish","scr_powerplay","scr_powerplay","scr_powerplay_beast_vanish" },
{ "scr_xm_orbital_blast","scr_xm_orbital","scr_xm_orbital","scr_xm_orbital_blast" },
{ "scr_emp_prop_light","scr_adversary","scr_adversary","scr_emp_prop_light" },

{ "scr_adversary_judgement_ash","scr_bike_adversary","scr_bike_adversary","scr_adversary_judgement_ash" },
{ "scr_adversary_ped_glow","scr_bike_adversary","scr_bike_adversary","scr_adversary_ped_glow" },
{ "scr_adversary_ped_light_good","scr_bike_adversary","scr_bike_adversary","scr_adversary_ped_light_good" },

{ "scr_adversary_ped_light_bad","scr_bike_adversary","scr_bike_adversary","scr_adversary_ped_light_bad" },
{ "scr_sm_con_ped_light","scr_sm","scr_sm","scr_sm_con_ped_light" },
{ "scr_sr_lg_weapon_highlight","scr_sr_adversary","scr_sr_adversary","scr_sr_lg_weapon_highlight" },
{ "scr_adversary_gunsmith_weap_change","scr_bike_adversary","scr_bike_adversary","scr_adversary_gunsmith_weap_change" },
{ "scr_apa_jacuzzi_wade","scr_apartment_mp","scr_apartment_mp","scr_apa_jacuzzi_wade" },
{ "scr_apa_jacuzzi_drips","scr_apartment_mp","scr_apartment_mp","scr_apa_jacuzzi_drips" },
{ "scr_as_trans_smoke","scr_as_trans","scr_as_trans","scr_as_trans_smoke" },
{ "scr_sm_con_trans","scr_sm_trans","scr_sm_trans","scr_sm_con_trans" },
{ "scr_sm_con_trans_fp","scr_sm_trans","scr_sm_trans","scr_sm_con_trans_fp" },
{ "scr_adversary_gunsmith_weap_change","scr_bike_adversary","scr_bike_adversary","scr_adversary_gunsmith_weap_change" },
{ "scr_adversary_gunsmith_weap_smoke","scr_bike_adversary","scr_bike_adversary","scr_adversary_gunsmith_weap_smoke" },
{ "scr_adversary_weap_glow","scr_bike_adversary","scr_bike_adversary","scr_adversary_weap_glow" },
{ "scr_heist_biolab_flare_underwater","scr_biolab_heist","scr_biolab_heist","scr_heist_biolab_flare_underwater" },
{ "scr_sr_tr_player_glow","scr_sr_tr","scr_sr_tr","scr_sr_tr_player_glow" },
{ "scr_xm_aq_final_kill_plane_delta","scr_xm_aq","scr_xm_aq","scr_xm_aq_final_kill_plane_delta" },
{ "scr_xm_aq_final_kill_plane_sweep","scr_xm_aq","scr_xm_aq","scr_xm_aq_final_kill_plane_sweep" },
{ "scr_xm_aq_final_kill_thruster","scr_xm_aq","scr_xm_aq","scr_xm_aq_final_kill_thruster" },
{ "scr_dst_cocaine","scr_ie_svm_technical2","scr_ie_svm_technical2","scr_dst_cocaine" },
{ "scr_drill_out","FM_Mission_Controler","FM_Mission_Controler","scr_drill_out" }
};


#pragma region ScreenVision
static std::vector<std::string> screenEffectName = {
	"SwitchHUDIn",
	"SwitchHUDOut",
	"FocusIn",
	"FocusOut",
	"MinigameEndNeutral",
	"MinigameEndTrevor",
	"MinigameEndFranklin",
	"MinigameEndMichael",
	"MinigameTransitionOut",
	"MinigameTransitionIn",
	"SwitchShortNeutralIn",
	"SwitchShortFranklinIn",
	"SwitchShortTrevorIn",
	"SwitchShortMichaelIn",
	"SwitchOpenMichaelIn",
	"SwitchOpenFranklinIn",
	"SwitchOpenTrevorIn",
	"SwitchHUDMichaelOut",
	"SwitchHUDFranklinOut",
	"SwitchHUDTrevorOut",
	"SwitchShortFranklinMid",
	"SwitchShortMichaelMid",
	"SwitchShortTrevorMid",
	"DeathFailOut",
	"CamPushInNeutral",
	"CamPushInFranklin",
	"CamPushInMichael",
	"CamPushInTrevor",
	"SwitchSceneFranklin",
	"SwitchSceneTrevor",
	"SwitchSceneMichael",
	"SwitchSceneNeutral",
	"MP_Celeb_Win",
	"MP_Celeb_Win_Out",
	"MP_Celeb_Lose",
	"LoseOut",
	"MP_Celeb_Lose_Out",
	"DeathFailNeutralIn",
	"DeathFailMPDark",
	"DeathFailMPIn",
	"MP_Celeb_Preload_Fade",
	"PeyoteEndOut",
	"PeyoteEndIn",
	"PeyoteIn",
	"PeyoteOut",
	"MP_race_crash",
	"SuccessFranklin",
	"SuccessTrevor",
	"SuccessMichael",
	"DrugsMichaelAliensFightIn",
	"DrugsMichaelAliensFight",
	"DrugsMichaelAliensFightOut",
	"DrugsTrevorClownsFightIn",
	"DrugsTrevorClownsFight",
	"DrugsTrevorClownsFightOut",
	"HeistCelebPass",
	"HeistCelebPassBW",
	"HeistCelebEnd",
	"HeistCelebToast",
	"MenuMGHeistIn",
	"MenuMGTournamentIn",
	"MenuMGSelectionIn",
	"ChopVision",
	"DMT_flight_intro",
	"DMT_flight",
	"DrugsDrivingIn",
	"DrugsDrivingOut",
	"SwitchOpenNeutralFIB5",
	"HeistLocate",
	"MP_job_load",
	"RaceTurbo",
	"MP_intro_logo",
	"HeistTripSkipFade",
	"MenuMGHeistOut",
	"MP_corona_switch",
	"MenuMGSelectionTint",
	"SuccessNeutral",
	"ExplosionJosh3",
	"SniperOverlay",
	"RampageOut",
	"Rampage",
	"Dont_tazeme_bro",
	"switch_cam_2",
	"switch_cam_1",
	"DefaultFlash",
	"PauseMenuOut",
	"SwitchShortNeutralMid",
	"SwitchOpenFranklinOut",
	"SwitchOpenMichaelOut",
	"SwitchOpenTrevorOut",
	"DeathFailMichaelIn",
	"DeathFailFranklinIn",
	"DeathFailTrevorIn",
	"BeastIntroScene",
	"BeastLaunch",
	"BeastTransition",
	"MP_OrbitalCannon",
	"MP_corona_switch_supermod",
	"WeaponUpgrade",
	"MP_Celeb_Lose_Out",
	"pennedIn",
	"PennedInOut",
	"CamPushInNeutral","CamPushInMichael",
	"CamPushInMichael","CamPushInNeutral",
	"SwitchOpenMichaelMid",
	"MenuMGHeistTint",
	"SwitchOpenNeutralOutHeist",
	"CrossLine",
	"CrossLineOut",
	"MP_SmugglerCheckpoint",
	"MP_WarpCheckpoint",
	"MP_TransformRaceFlash",
	"MP_Celeb_Preload",
	"InchOrange",
	"InchPurple",
	"InchPickup",
	"PPOrange",
	"PPPurple",
	"PPGreen",
	"PPPink",
	"DeadlineNeon",
	"InchPickupOut",
	"PPOrangeOut",
	"PPPurpleOut",
	"PPGreenOut",
	"PPPinkOut",
	"LostTimeDay",
	"LostTimeNight",
	"MP_Bull_tost",
	"PPFilterOut",
	"PPFilter",
	"TinyRacerPink",
	"TinyRacerGreen",
	"TinyRacerGreenOut",
	"TinyRacerPinkOut",
	"InchOrangeOut",
	"InchPurpleOut",
	"TinyRacerIntroCam",
	"BikerFormation",
	"BikerFormationOut",
	"SwitchOpenFranklin",
	"SwitchHUDMichaelIn",
	"SwitchHUDFranklinIn",
	"SwitchHUDTrevorIn",
	"MenuMGIn",
	"MenuMGOut",
	"MenuMGTournamentTint",
	"MenuMGHeistIntro"
};
static std::vector<std::string> Vison =
{
	"V_FIB_IT3",
	"scanline_cam",
	"mp_x17dlc_int_02_weapon_avenger_camera",
	"CAMERA_secuirity_FUZZ",
	"mp_bkr_ware02_upgrade",
	"mp_bkr_ware03_upgrade",
	"CAMERA_secuirity",
	"mp_bkr_ware02_standard",
	"mp_bkr_ware03_basic",
	"spectator1",
	"spectator2",
	"spectator3",
	"spectator4",
	"spectator5",
	"spectator6",
	"spectator7",
	"spectator8",
	"spectator9",
	"spectator10",
	"mp_x17dlc_int_02_tint1",
	"mp_x17dlc_int_02_tint2",
	"mp_x17dlc_int_02_tint3",
	"mp_x17dlc_int_02_tint4",
	"mp_x17dlc_int_02_tint5",
	"mp_x17dlc_int_02_tint6",
	"mp_x17dlc_int_02_tint7",
	"mp_x17dlc_int_02_tint8",
	"mp_x17dlc_int_02_tint9",
	"mp_x17dlc_int_02_vehicle_workshop_camera",
	"RemixDrone",
	"mp_battle_int03_tint1",
	"mp_battle_int03_tint2",
	"mp_battle_int03_tint3",
	"mp_battle_int03_tint4",
	"mp_battle_int03_tint5",
	"mp_battle_int03_tint6",
	"mp_battle_int03_tint7",
	"mp_battle_int03_tint8",
	"mp_battle_int03_tint9",
	"mp_battle_int01_dancefloor_OFF",
	"eyeinthesky",
	"phone_cam",
	"Hint_cam",
	"mp_x17dlc_int_02_vehicle_avenger_camera",
	"INT_smshop_inMOD",
	"heliGunCam",
	"crane_cam",
	"crane_cam_cinematic",
	"exile1_plane",
	"chop",
	"canyon_mission",
	"sunglasses",
	"stoned_monkeys",
	"stoned_aliens",
	"STONED_CUTSCENE",
	"telescope",
	"scanline_cam_cheap",
	"traffic_skycam",
	"MP_select",
	"NoPedLight",
	"mp_lad_judgment",
	"grdlc_int_02",
	"secret_camera",
	"RemoteSniper",
	"graveyard_shootout",
	"micheals_lightsOFF",
	"DRUG_gas_huffin",
	"drug_wobbly",
	"player_transition_scanlines",
	"cashdepot",
	"Drug_deadman",
	"trailer_explosion_optimise"
};
#pragma endregion



